name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations, you just submitted your first issue, Welcome to the family.'' first issue'
        pr-message: 'Congratulations, you just submitted your first pull request, Welcome to the deep family'' first pr'
